{
 "title": "KeeperBench",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server_disk", "query": "${VAR_SERVER_DISK}" }
  ]
 },
 "panels": [
  { "title": "KeeperBench", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate (last 1m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(keeper_bench_requests_executed[1m]) and keeper_bench_requests_executed offset 1m)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(keeper_bench_requests_executed[1m]) and keeper_bench_requests_executed offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (last 3m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(keeper_bench_requests_executed[$__rate_interval]))",
     "legendFormat": "Rate"
    },
    {
     "expr": "sum(rate(keeper_bench_requests_executed[1m]) and (keeper_bench_requests_executed offset 1m and keeper_bench_requests_executed)) ",
     "legendFormat": "Rate (1m)"
    }
   ]
  },
  {
   "title": "Requests Rate (By Type)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperCreate[$__rate_interval]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperRemove[$__rate_interval]))",
     "legendFormat": "Remove"
    },
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperSet[$__rate_interval]))",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperGet[$__rate_interval]))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperList[$__rate_interval]))",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "Request Latency (last 1m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / sum(rate(keeper_bench_requests_executed[1m]) and keeper_bench_requests_executed offset 1m) * sum(keeper_bench_concurrency)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 / sum(rate(keeper_bench_requests_executed[1m]) and keeper_bench_requests_executed offset 1m) * sum(keeper_bench_concurrency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (last 3m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m) * sum(keeper_bench_concurrency)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 / sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m) * sum(keeper_bench_concurrency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(1 / rate(keeper_bench_requests_executed[$__rate_interval]) * keeper_bench_concurrency and (keeper_bench_concurrency offset $__rate_interval))",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg(1 / rate(keeper_bench_requests_executed[1m]) * keeper_bench_concurrency and (keeper_bench_concurrency offset 1m))",
     "legendFormat": "Latency (1m)"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(keeper_bench_concurrency)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(keeper_impl) (keeper_bench_concurrency)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests on Fly",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(keeper_bench_ZooKeeperRequest[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read%",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(keeper_bench_ZooKeeperList[$__rate_interval]) + rate(keeper_bench_ZooKeeperGet[$__rate_interval])) / sum(rate(keeper_bench_ZooKeeperCreate[$__rate_interval]) + rate(keeper_bench_ZooKeeperSet[$__rate_interval]) + rate(keeper_bench_ZooKeeperRemove[$__rate_interval]) + rate(keeper_bench_ZooKeeperList[$__rate_interval]) + rate(keeper_bench_ZooKeeperGet[$__rate_interval]))",
     "legendFormat": "Read%"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(keeper_bench_requests_error[$__rate_interval]) / (rate(keeper_bench_requests_error[$__rate_interval]) + rate(keeper_bench_requests_executed[$__rate_interval])))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "avg(rate(keeper_bench_requests_error[1m]) / (rate(keeper_bench_requests_error[1m]) + rate(keeper_bench_requests_executed[1m])))",
     "legendFormat": "Error Rate (1m)"
    }
   ]
  },
  {
   "title": "Write Latency Quantile",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keeper_bench_write{quantile=\"50\"})",
     "legendFormat": "P50"
    },
    {
     "expr": "max(keeper_bench_write{quantile=\"90\"})",
     "legendFormat": "P90"
    },
    {
     "expr": "max(keeper_bench_write{quantile=\"99\"})",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Performance CSV",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 16 },
   "options": {
    "content": "``` csv\nconcurrency,ops,latency_s\n{{#each data}}{{json this.[0].Value}}{{#unless @last}},{{/unless}}{{/each}}\n```"
   },
   "targets": [
    { "expr": "sum(keeper_bench_concurrency)", "legendFormat": "__auto" },
    {
     "expr": "sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 / sum(rate(keeper_bench_requests_executed[3m]) and keeper_bench_requests_executed offset 3m) * sum(keeper_bench_concurrency)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KeeperBench (By Range)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(timestamp(keeper_bench_requests_executed)[$__range:1s])) - min(min_over_time(timestamp(keeper_bench_requests_executed)[$__range:1s])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FileSystem Usage Increase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(-delta(node_filesystem_free_bytes{device=~\"/dev/${server_disk}.*\",instance=~\"s.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Cpu",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(100 - (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"s.*\"}[$__rate_interval])) * 100)[$__range:1s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(node_memory_MemTotal_bytes{instance=~\"s.*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)[$__range:1s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Summary CSV",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 27 },
   "options": {
    "content": "``` csv\ntotal_s,fs_inc,max_cpu,max_mem\n{{#each data}}{{json this.[0].Value}}{{#unless @last}},{{/unless}}{{/each}}\n```"
   },
   "targets": [
    {
     "expr": "max(max_over_time(timestamp(keeper_bench_requests_executed)[$__range:1s])) - min(min_over_time(timestamp(keeper_bench_requests_executed)[$__range:1s])) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(-delta(node_filesystem_free_bytes{device=~\"/dev/${server_disk}.*\",instance=~\"s.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(sum(100 - (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"s.*\"}[$__rate_interval])) * 100)[$__range:1s])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "max_over_time(sum(node_memory_MemTotal_bytes{instance=~\"s.*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)[$__range:1s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KeeperBench (By Instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Request Rate",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(keeper_bench_requests_executed[$__rate_interval])",
     "legendFormat": "{{instance}} ({{keeper_impl}})"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/ rate(keeper_bench_requests_executed[$__rate_interval]) * keeper_bench_concurrency",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Write Latency Summary",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "keeper_bench_write{quantile=\"50\"}",
     "legendFormat": "P50 ({{instance}})"
    },
    {
     "expr": "keeper_bench_write{quantile=\"99\"}",
     "legendFormat": "P99 ({{instance}})"
    },
    {
     "expr": "keeper_bench_write_sum / keeper_bench_write_count / 1000",
     "legendFormat": "Avg ({{instance}})"
    },
    {
     "expr": "keeper_bench_write{quantile=\"90\"}",
     "legendFormat": "P90 {{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(keeper_bench_requests_error[$__rate_interval]) / (rate(keeper_bench_requests_error[$__rate_interval]) + rate(keeper_bench_requests_executed[$__rate_interval]))",
     "legendFormat": "Error Rate ({{instance}})"
    },
    {
     "expr": "rate(keeper_bench_requests_error[1m]) / (rate(keeper_bench_requests_error[1m]) + rate(keeper_bench_requests_executed[1m]))",
     "legendFormat": "Error Rate (1m) ({{instance}})"
    }
   ]
  },
  {
   "title": "FDBClient Busyness",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "keeper_bench_FDBClientBusyness > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Create Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(keeper_bench_ZooKeeperTransactions[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Latency Summary",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "keeper_bench_read{quantile=\"50\"}",
     "legendFormat": "P50 ({{instance}})"
    },
    {
     "expr": "keeper_bench_read{quantile=\"99\"}",
     "legendFormat": "P99 ({{instance}})"
    },
    {
     "expr": "keeper_bench_read_sum / keeper_bench_read_count / 1000",
     "legendFormat": "Avg ({{instance}})"
    }
   ]
  },
  { "title": "FoundationDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Roles",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(role) (fdb_cluster_process_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(fdb_cluster_process_cpu_usage[$__rate_interval])",
     "legendFormat": "{{address}} - {{class_type}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(fdb_cluster_latency_probe_transaction_start_seconds[$__rate_interval])",
     "legendFormat": "GRV"
    },
    {
     "expr": "avg_over_time(fdb_cluster_latency_probe_read_seconds[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "avg_over_time(fdb_cluster_latency_probe_commit_seconds[$__rate_interval])",
     "legendFormat": "Commit"
    },
    {
     "expr": "avg_over_time(fdb_cluster_latency_probe_commit_seconds[1m])",
     "legendFormat": "Commit (1m)"
    }
   ]
  },
  {
   "title": "Transactions Qos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "fdb_cluster_qos_transactions_per_second_limit < 1000000",
     "legendFormat": "QOS"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fdb_cluster_workload_transactions_committed[30s])",
     "legendFormat": "Commited"
    },
    {
     "expr": "rate(fdb_cluster_workload_transactions_conflicted[30s])",
     "legendFormat": "Conflicted"
    }
   ]
  },
  {
   "title": "Transactions Conflict Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fdb_cluster_workload_transactions_conflicted[30s]) / (rate(fdb_cluster_workload_transactions_conflicted[30s]) + rate(fdb_cluster_workload_transactions_committed[30s]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 49 },
   "targets": [
    { "expr": "fdb_cluster_process_role", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fdb_cluster_workload_operations_reads[30s])",
     "legendFormat": "30s"
    },
    {
     "expr": "rate(fdb_cluster_workload_operations_reads[3m])",
     "legendFormat": "3m"
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fdb_cluster_workload_operations_writes[30s])",
     "legendFormat": "30s"
    },
    {
     "expr": "rate(fdb_cluster_workload_operations_writes[3m])",
     "legendFormat": "3m"
    }
   ]
  },
  {
   "title": "Key/Second CSV",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 55 },
   "options": {
    "content": "``` csv\nread_keys_ps,write_keys_ps\n{{#each data}}{{json this.[0].Value}}{{#unless @last}},{{/unless}}{{/each}}\n```"
   },
   "targets": [
    {
     "expr": "rate(fdb_cluster_workload_operations_reads[3m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(fdb_cluster_workload_operations_writes[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Internal IPv4",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 62 },
   "targets": [
    { "expr": "node_internal_ipv4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Load 1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 62 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Transmit Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Receive Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"s.*\",device=\"$server_disk\"}[$__rate_interval]) / (rate(node_disk_writes_completed_total{device=\"$server_disk\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"s.*\",device=\"$server_disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"s.*\",device=\"$server_disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{device=~\"/dev/${server_disk}.*\",instance=~\"s.*\"} / node_filesystem_size_bytes{device=~\"/dev/${server_disk}.*\",instance=~\"s.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}