global:
  scrape_interval: 15s
scrape_configs:
  - job_name: keeper-bench
    scrape_interval: 1s
    file_sd_configs:
      - files: [/etc/prometheus/keeper-bench.yaml]
        refresh_interval: 1m
    honor_labels: true
